/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import { BaseContract } from "ethers";
export class UniswapInterfaceMulticall extends BaseContract {
  constructor() {
    super(...arguments);
    this.interface = void 0;
    this.functions = void 0;
    this.callStatic = void 0;
    this.filters = void 0;
    this.estimateGas = void 0;
    this.populateTransaction = void 0;
  }

}